---
- hosts: all
  tasks:
    - name: Add  user to the sudoers
      copy:
        dest: "/etc/sudoers.d/anna"
        content: |
          anna ALL = NOPASSWD: ALL
          anna ALL = (ALL) NOPASSWD:ALL
      become: yes

    - name: Add local SSH key
      copy:
        dest: "/home/anna/.ssh/authorized_keys"
        content:
            "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDp4fT+PNGXZKJ9mGVrXeNUYgxSQ5HNckW0Fc5yHWc1O7cRnYqqb/8Wp1wpAFX56A0TUJ8zISLdxUc5iLA7c6rd1dQi9F0iVXoS6TF5NBWwi4G6JyCc3ymTokJ6mq6nyUead8Rso+21MrRkmSumU/i>"
      become: yes

- hosts: vm2
  tasks:
    - name: ensure nginx is at the latest version
      apt:
        name: nginx
        state: latest
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes

- hosts: vm3
  vars:
    download_url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.8/bin/apache-tomcat-10.1.8.tar.gz
  tasks:
   - name: Download Open JDK
     become: yes
     apt:
      name: openjdk-8-jre-headless
      update_cache: yes
      state: present

   - name: validate if Java is availble
     shell:
      java -version

   - name: Create the group
     become: yes
     group:
      name: tomcat
      state: present
   - name: Create the user
     become: yes
     user:
        name: tomcat
        state: present
   - name: Create a Directory /opt/tomcat10
     become: yes
     file:
       path: /opt/tomcat10
       state: directory
       mode: 0755
       owner: tomcat
       group: tomcat
   - name: Create a Tomcat Directory
     file:
       path: /opt/tomcat10
       owner: tomcat
       group: tomcat
       mode: 755
       recurse: yes

   - name: download & unarchive tomcat10
     unarchive:
       src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.8/bin/apache-tomcat-10.1.8.tar.gz
       dest: /opt/tomcat10
       remote_src: yes
       extra_opts: [--strip-components=1]

   - name: Change ownership of tomcat directory
     file:
       path: /opt/tomcat10
       owner: tomcat
       group: tomcat
       mode: u=rwx,g=rx,o=rx
       recurse: yes
       state: directory
   - name: Creating a service file
     become: yes
     copy:
       content: |-
        [Unit]
        Description=Tomcat Service
        Requires=network.target
        After=network.target
        [Service]
        Type=forking
        User=tomcat
        Environment="CATALINA_PID=/opt/tomcat10/logs/tomcat.pid"
        Environment="CATALINA_BASE=/opt/tomcat10"
        Environment="CATALINA_HOME=/opt/tomcat10"
        Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
        ExecStart=/opt/tomcat10/bin/startup.sh
        ExecStop=/opt/tomcat10/bin/shutdown.sh
        Restart=on-abnormal
        [Install]
        WantedBy=multi-user.target
       dest: /etc/systemd/system/tomcat.service

   - name: Reload the SystemD to re-read configurations
     become: yes
     systemd:
       daemon-reload: yes
   - name: Enable the tomcat service and start
     become: yes
     systemd:
       name: tomcat
       enabled: yes
       state: started
